# HTTP server to handle ACME challenge and redirect other traffic to HTTPS
server {
    listen 80;
    server_name my-star.duckdns.org *.my-star.duckdns.org;
    
    # This location is used by Certbot for the ACME challenge.
    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }
}

