services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443" # HTTPS served on port 3003
      - "80:80" # Standard HTTP port for Certbot
      - "88:88" # Your custom port for n8n webhooks
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Your config file
      - certs:/etc/letsencrypt # Shared volume for certs
      - ./www:/usr/share/nginx/html

  # certbot:
  #   # This is the fix. It tells Docker to build your custom image from the Dockerfile.
  #   build: .
  #   container_name: certbot-duckdns
  #   volumes:
  #     - certs:/etc/letsencrypt
  #   env_file:
  #     - .env
  #   command:  |
  #     certonly --non-interactive --agree-tos --email alexepp@gmail.com
  #     --authenticator dns-duckdns
  #     --dns-duckdns-token ${DUCKDNS_TOKEN}
  #     --dns-duckdns-propagation-seconds 120
  #     -d my-star.duckdns.org
  #     -d *.my-star.duckdns.org
  #     --expand

volumes:
  certs:
  html:
