services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"    # HTTPS served on port 3003
      - "80:80"       # Standard HTTP port for Certbot
      - "88:88"       # Your custom port for n8n webhooks
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Your config file
      - certs:/etc/letsencrypt # Shared volume for certs
      # Mount the demo HTML files into the container
      - ./www:/usr/share/nginx/html

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   restart: unless-stopped
  #   volumes:
  #     - certs:/etc/letsencrypt
  #     - html:/usr/share/nginx/html
  #   # Initial run: this command obtains the certificate using the webroot method.
  #   # After the first successful run, you can comment it out and set up a cron job or similar.
  #   command: certonly --webroot --webroot-path=/usr/share/nginx/html --agree-tos --email alexepp@gmail.com -d my-star.duckdns.org --non-interactive

volumes:
  certs:
  html:
